image: python:3.9-slim

pages:
  stage: deploy
  script:
    - apt update -y
    - apt install -y libgomp1
    - pip install -e .
    - pip install -U sphinx sphinx-rtd-theme
    - sphinx-build -b html ./docs ./public
  artifacts:
    paths:
    - public
    expire_in: 1 week
  only:
    refs:
      - master
    changes:
      - docs/*
      - docs/**/*
      - var_mesh/version.py
