image: python:3.8-alpine

pages:
  stage: deploy
  script:
    - pip install -U sphinx sphinx-rtd-theme
    - cd docs/
    - sphinx-build -b html . ../public
  artifacts:
    paths:
    - public
  only:
  - docs
