image: python:3.8-slim

pages:
  stage: deploy
  script:
    - apt update -y
    - apt install -y libgomp1
    - pip install -e .
    - pip install -U sphinx sphinx-rtd-theme
    - sphinx-build -b html ./docs ./public
  artifacts:
    paths:
    - public
  only:
    refs:
      - docs
    changes:
      - .gitlab-ci.yml
      - docs/*
      - docs/**/*
